BLURBS = [
    "New York is a key commercial hub with significant urban development and diverse industries. With a large and growing population of around 800,000, New York supports industrial jobs and benefits from a popular vote system, leveraging its populous nature to gain significant influence. The state accrued less debt than others but remains pro-bailout, favoring federal assistance to manage its finances. New York’s merchants benefit from import tariffs that protect local industries, opposing export taxes to maintain its trade dominance. High taxes on imports safeguard thriving local businesses from foreign competition. New York reported roughly 20,000 enslaved people, fewer than other states, and seeks to maintain autonomy in trade policies rather than being subjected to national legislation.",
    
    "Massachusetts is a bustling industrial and maritime center with a population of around 380,000. As one of the largest states in the Union, Massachusetts gains from a popular vote system, enhancing its influence due to its sizable population. The state's bustling ports fuel the economy through imports and exports, supporting import tariffs to protect local industries while opposing export taxes that could harm its merchants. Massachusetts advocates for strong federal control over interstate trade to ensure standardized regulations and efficient trade routes. A staunch abolitionist, Massachusetts opposes any policies that would increase the power of slavery-dependent regions. The state has accrued heavy costs from the Revolutionary War, favoring federal relief to ease war debts. Guided by strong moral convictions, Massachusetts champions a strong federal government to regulate trade and unify the states, ensuring stability and growth for its people and industries.",
    
    "Georgia's economy is deeply rooted in large-scale agriculture, with a strong dependence on slave labor for its plantations. With a population of approximately 300,000, Georgia benefits from equal representation in Congress, ensuring its agricultural interests are equally voiced. The state imposes high taxes on exports to secure favorable conditions for its agricultural goods in global markets and opposes export taxes that could harm its export-based economy. Georgia favors no federal control over interstate trade, preferring to handle its own trade agreements and regulations to benefit its agricultural sector. Upholding its economic structure, Georgia is firmly against abolishing slavery and seeks to protect the institution. For infrastructure, Georgia advocates for low federal funding, preferring state-managed projects that directly support its agricultural exports. With very low war debts, Georgia opposes a federal bailout, preferring to manage its finances independently.",
    
    "South Carolina is heavily reliant on its agricultural economy, particularly plantation-based crops, and has a population of around 280,000. To protect its influence in Congress, South Carolina insists on equal representation for all states, regardless of population size. The state imposes high taxes on exports to protect and subsidize its agricultural products in international markets and opposes export taxes that could hinder its export economy. South Carolina advocates for no federal control over interstate trade, allowing it to manage its own agricultural trade policies independently. Maintaining its plantation economy, South Carolina strongly opposes abolitionist policies and seeks to protect slavery as a vital labor system. For infrastructure, South Carolina prefers low federal funding, favoring state-managed projects that specifically support its agricultural export needs. With one of the highest war debts, South Carolina opposes a federal bailout, preferring to handle its debts independently.",
    
    "Pennsylvania has a population of approximately 434,000 and a small enslaved population of about 4,000. The state supports a system of equal representation in Congress, advocating for each state to have one vote, which reflects Pennsylvania's smaller population but strong industrial base. Pennsylvania's growing manufacturing sector relies on internal improvements and federal regulation for economic growth, favoring protective tariffs on imports to shield its industries while maintaining significant agricultural exports like wheat. The state supports more federal control over trade regulation to ensure consistent policies that benefit its diverse economy. Pennsylvania contributed a hefty amount to the Revolutionary War and supports federal assistance to manage war debts, aligning with Northern interests to limit Southern influence.",
    
    "Virginia is the most populated state in America as of 1790, with a population of about 747,000 people, including approximately 292,000 slaves. As an agrarian state with a robust tobacco economy, Virginia's interests in the Constitutional Convention are shaped by its reliance on slave labor and agricultural exports. Given its large population and significant rural areas, Virginia favors the Electoral College system. This preference allows Virginia to leverage both its populous nature and its rural interests, ensuring that state-based voting power remains influential in national elections. Additionally, the Electoral College helps balance the interests of Virginia's diverse population, including its large number of enslaved individuals, without granting direct voting rights to slaves, which Virginia firmly opposes. In terms of taxation, Virginia is cautious about heavy taxes on exports, particularly tobacco, a major revenue source. The state opposes strong federal control over interstate and foreign trade, fearing it could limit its economic independence and agricultural exports. Virginia contributed the second highest amount to the Revolutionary War and opposes federal bailouts, preferring to manage its own finances."
]
